name: 'Delete old artifacts'
on:
  schedule:
    - cron:  '*/1 * * * *'
jobs:
  delete-artifacts:
    uses: syedsalman3753/kattu/.github/workflows/clear-artifacts.yml@master
    secrets:
      ACCESS_TOKEN: ${{ secrets.access_token }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
